### ISSUE TITLE
Feature 1 - user can see their car

### ISSUE THREAD

**Issue by m-Cho1** [m-Cho1/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] add background color to display racing field
- [x] add racing car image to display the car to user
- [x] remove unnecessary CSS features
- [x] check for errors
