### ISSUE TITLE
Feature 2 -User can start their car

### ISSUE THREAD

**Issue by m-Cho1** [m-Cho1/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [ ] make the car's image absolute, and set the position
- [ ] make the image move when user press a right arrow key
- [ ] make the image move straight to the left
- [ ] make the image move every 16 milliseconds for a smooth movement
- [ ] remove unnecessary CSS styles
- [ ] check for errors
